version: '3'
services:
  master:
    image: 'ros:kinetic-ros-core-xenial'
    command:
      - roscore

  turtlesim:
    image: 'osrf/ros:kinetic-desktop'
    environment:
      - "ROS_HOSTNAME=turtlesim"
      - "ROS_MASTER_URI=http://master:11311"
      - "DISPLAY=${HOSTNAME?err}:0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rosrun turtlesim turtlesim_node 
